#-------------------------------
# General Site Settings

title: Rahul Avadhoot
email: rahul.avadhoot@gmail.com
address: 1741 Camden Ave, Los Angeles, CA 90025

menu:
- {name: About, link: '/about.html'}
- {name: Blog, link: '/blog.html'}
- {name: Portfolio, link: '/portfolio.html'}
- {name: Contact, link: '/contact.html'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Rahul <br> a Data Science professional

social:
- {icon: "ti-linkedin", link: "https://linkedin.com/in/rahulavadhoot"}
- {icon: "ti-github", link: "https://github.com/rahulavadhoot"}
- {icon: "ti-twitter", link: "https://twitter.com/rahulavadhoot"}
- {icon: "ti-instagram", link: "https://www.instagram.com/rahulavadhoot/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Data Scientist with a background in chemical engineering and 3 years experience in machine learning, cheminformatics, and data science. Passionate about building data-driven products for chemical, biological, and business data.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research"
    icon : "assets/images/icons/plan.png"
    content : "Research solutions to business problems"
    
  - title : "Develop"
    icon : "assets/images/icons/design.png"
    content : "Develop prototype solutions and improve iteratively"
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Deliver scalable solutions as a final product"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Python, value: '100%', color: '#fdb157'}
- {name: SQL, value: '70%', color: '#fdb157'}
- {name: Machine Learning, value: '85%', color: '#ffbcaa'}
- {name: Data Engineering, value: '80%', color: '#ffbcaa'}
- {name: Business Intelligence, value: '70%', color: '#ffbcaa'}
- {name: Cheminformatics, value: '90%', color: '#9473e6'}


#-------------------------------
# Experience Section

experience-title: Experience
experience:
- {name: Data Analyst, icon: 'icon-3.png', date: 'Jun 2020 - Present', organization: 'Darcy Partners'}
- {name: Data Science Resident, icon: 'icon-2.png', date: 'Apr 2019 - Mar 2020', organization: 'Qulab'}
- {name: Process Engineer, icon: 'icon-1.png', date: 'Jul 2015 - Jul 2016', organization: 'Reliance Industries'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Master of Science in Chemical Engineering, date: '2018', organization: 'University of Washington'}
- {name: Minor in Data Science, date: '2018', organization: 'University of Washington'}
- {name: Bachelor of Technology in Chemical Engineering, date: '2015', organization: 'Visvesvaraya National Institute of Technology'}


#-------------------------------
# Services Section

services-title: Specialities
services:
- {
    name: Predictive Modeling,
    icon: ti-palette,
    description: 'Scalable machine learning solutions',
    active: # Add true to select section
  }
- {
    name: BI Dashboarding,
    icon: ti-vector,
    description: 'Power BI and Tableau dashboards to drive business insight',
    active: true # Add true to select section
  }
- {
    name: Data Science Tools,
    icon: ti-panel,
    description: "Tools for data cleaning, transformation and visualization",
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "Machine learning",
    type : "ml"
  }
- {
    title : "Business Intelligence",
    type : "bi"
  }
- {
    title : "Cheminformatics",
    type : "cix"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "https://github.com/rahulavadhoot/data-science-portfolio"
    portfolio-type:
     - type: "ml"


#-------------------------------
# Client Slider Section


#-------------------------------
# Contact Section

contact-title: Contact
contact-email: rahul.avadhoot@gmail.com