#-------------------------------
# General Site Settings

title: Rahul Avadhoot
logo: logo.png
email: rahul.avadhoot@gmail.com
address: 1741 Camden Ave, Los Angeles, CA 90025

menu:
- {name: About, link: '/about.html'}
- {name: Blog, link: '/blog.html'}
- {name: Portfolio, link: '/portfolio.html'}
- {name: Contact, link: '/contact.html'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Rahul <br> Data Scientist

social:
- {icon: "ti-linkedin", link: "https://linkedin.com/in/rahulavadhoot"}
- {icon: "ti-github", link: "https://github.com/rahulavadhoot"}
- {icon: "ti-twitter", link: "https://twitter.com/rahulavadhoot"}
- {icon: "ti-instagram", link: "https://www.instagram.com/rahulavadhoot/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Data Scientist with a background in chemical engineering and 3 years experience in machine learning, cheminformatics, and data science. Passionate about building data-driven products for chemical, biological, and business data. My interests include machine learning, artificial intelligence, big-data analytics, cheminformatics, evolutionary algorithms, and databases.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "hello world"
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "hello world"
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "hello world"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Machine Learning, color: '#fdb157', value: '80%'}
- {name: Cheminformatics, color: '#9473e6', value: '80%'}
- {name: Business Intelligence, color: '#bdecf6', value: '60%'}
- {name: Data Science, color: '#ffbcaa', value: '90%'}


#-------------------------------
# Experience Section

experience-title: Experience
experience:
- {name: Process Engineer, icon: 'icon-1.png', date: 'Jul 2015 - Jul 2016', organization: 'Reliance Industries'}
- {name: Data Science Resident, icon: 'icon-2.png', date: 'Apr 2019 - Mar 2020', organization: 'Qulab'}
- {name: Data Analyst, icon: 'icon-3.png', date: 'Jun 2020 - Present', organization: 'Darcy Partners'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Master of Science in Chemical Engineering, date: '2018', organization: 'University of Washington'}
- {name: Minor in Data Science, date: '2018', organization: 'University of Washington'}
- {name: Bachelor of Technology in Chemical Engineering, date: '2015', organization: 'Visvesvaraya National Institute of Technology'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Predictive Modeling,
    icon: ti-palette,
    description: 'Hello world',
    active: # Add true to select section
  }
- {
    name: BI Dashboarding,
    icon: ti-vector,
    description: 'hello world',
    active: true # Add true to select section
  }
- {
    name: Data Science Tools,
    icon: ti-panel,
    description: 'hello world',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"



#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: rahul.avadhoot@gmail.com